export default function TermsPage() {
  return (
    <div className="space-y-8 max-w-2xl">
      <div>
        <h2 className="text-lg font-semibold text-white">Terms, Privacy & Disclaimer</h2>
        <p className="text-white/40 text-sm mt-0.5">Last updated: May 2026</p>
      </div>

      {/* Tabs */}
      <div className="space-y-6">
        {/* Disclaimer */}
        <div className="card-glass rounded-2xl p-6 border border-amber-500/20 bg-amber-500/5">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-7 h-7 rounded-lg bg-amber-500/20 flex items-center justify-center shrink-0">
              <svg className="w-3.5 h-3.5 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <p className="text-amber-300 font-semibold text-sm">Cosmetic-Only Disclaimer</p>
          </div>
          <div className="space-y-2 text-white/50 text-sm leading-relaxed">
            <p>SKINIC is an <strong className="text-white/70">AI-powered cosmetic skin analysis tool, not a medical device</strong>. Results generated by the SKINIC API are for informational, cosmetic, and beauty purposes only.</p>
            <p>SKINIC results <strong className="text-white/70">do not constitute medical advice, diagnosis, or treatment</strong>, and do not detect or assess any disease or medical condition.</p>
            <p>By using this API, you agree to communicate this disclaimer clearly to your end users and obtain appropriate consent.</p>
          </div>
        </div>

        {/* Terms of Service */}
        <div className="card-glass rounded-2xl p-6">
          <p className="text-white font-semibold text-sm mb-4">Terms of Service</p>
          <div className="space-y-3 text-white/45 text-sm leading-relaxed">
            <p><strong className="text-white/70">1. Acceptable Use.</strong> You may use the SKINIC API only for lawful purposes. You must not resell, sublicense, or redistribute API access without written consent.</p>
            <p><strong className="text-white/70">2. User Consent.</strong> You must obtain explicit consent from your end users before collecting or processing any biometric or skin image data.</p>
            <p><strong className="text-white/70">3. Rate Limits.</strong> You agree to respect the rate limits and monthly call caps assigned to your tier. Abuse may result in account suspension.</p>
            <p><strong className="text-white/70">4. Key Security.</strong> You are responsible for keeping your API keys secure. Do not expose keys in client-side code or public repositories.</p>
            <p><strong className="text-white/70">5. Modifications.</strong> SKINIC reserves the right to modify pricing, rate limits, and features with reasonable notice.</p>
            <p><strong className="text-white/70">6. Termination.</strong> We reserve the right to suspend or terminate access for violations of these terms.</p>
          </div>
        </div>

        {/* Privacy Policy */}
        <div className="card-glass rounded-2xl p-6">
          <p className="text-white font-semibold text-sm mb-4">Privacy Policy</p>
          <div className="space-y-3 text-white/45 text-sm leading-relaxed">
            <p><strong className="text-white/70">Data We Collect.</strong> We collect your name, email, company, and API usage metadata (call counts, timestamps). We do not store skin images after processing.</p>
            <p><strong className="text-white/70">How We Use It.</strong> Data is used solely to provide the SKINIC API service, manage your account, and improve our models. We do not sell your data.</p>
            <p><strong className="text-white/70">Data Storage.</strong> Data is stored in Supabase (PostgreSQL) hosted on AWS. We apply encryption at rest and in transit.</p>
            <p><strong className="text-white/70">Retention.</strong> Account data is retained for the duration of your subscription plus 90 days. You may request deletion at any time.</p>
            <p><strong className="text-white/70">Third Parties.</strong> We use Paddle as our Merchant of Record for payment processing. Your payment data is never stored by SKINIC.</p>
            <p><strong className="text-white/70">Contact.</strong> For data requests or privacy concerns, email <a href="mailto:skinic@thinkingstudio.ai" className="text-violet-400">skinic@thinkingstudio.ai</a>.</p>
          </div>
        </div>

        {/* PDPA / GDPR note */}
        <div className="card-glass rounded-2xl p-5 border border-white/5">
          <p className="text-white/40 text-xs leading-relaxed">
            SKINIC complies with applicable data protection laws including PDPA (Malaysia) and GDPR principles.
            For enterprise compliance requirements (SOC 2, GDPR), contact{" "}
            <a href="mailto:skinic@thinkingstudio.ai?subject=Compliance%20Inquiry" className="text-violet-400">skinic@thinkingstudio.ai</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
