import Link from "next/link";

export const metadata = {
  title: "Terms of Service — SKINIC",
  description: "Terms of Service for SKINIC AI Skin Intelligence — Studio and API products.",
};

const sections = [
  {
    title: "1. Agreement to Terms",
    body: `By accessing or using any SKINIC product — including SKINIC Studio (skinic.app), the SKINIC API (api.skinic.app), dashboard, or any related services operated by Thinking Studio LLC ("Company", "we", "us", "our") — you ("Client", "you") agree to be bound by these Terms of Service ("Terms").\n\nIf you are using our services on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms. If you do not agree, you must not use our services.`,
  },
  {
    title: "2. Description of Service",
    body: `SKINIC operates two distinct products under a single account:\n\n2.1 SKINIC Studio (skinic.app/studio)\nA no-code platform that enables beauty businesses — including salons, aesthetic studios, beauty brands, and retailers — to launch a branded AI skin profiling page, build a product and service catalog, capture customer leads, and view analytics. Studio clients ("Studio Clients") use the platform to serve their own end users ("Studio End Users") via a branded scan page.\n\n2.2 SKINIC API (api.skinic.app)\nA REST API that provides programmatic access to skin-type profiling, visible trait scoring, ingredient guidance, and skin embeddings, for integration into third-party applications, platforms, and workflows by developers ("API Clients").\n\nBoth products are for cosmetic and informational purposes only. SKINIC is positioned as a cosmetic beauty tool — not a medical device and not intended for clinical screening. Regulatory requirements vary by country and market; see Section 24.`,
  },
  {
    title: "3. Account Registration & Security",
    body: `You must provide accurate and complete information when creating your account. You are responsible for maintaining the confidentiality of your login credentials and API keys. You must notify us immediately at skinic@thinkingstudio.ai if you suspect unauthorised access to your account. We reserve the right to disable accounts we believe are compromised.\n\nAPI Clients: Each API key must be used only by the authorised application for which it was issued.\n\nStudio Clients: Your Studio account governs your branded scan page, catalog, and customer database. You are responsible for securing access to your Studio dashboard and for all activity conducted through your branded scan page.`,
  },
  {
    title: "4. Acceptable Use",
    body: `You agree to use SKINIC only for lawful purposes and in compliance with all applicable local, national, and international laws and regulations.\n\nAll Clients must not:\n• Attempt to reverse-engineer, decompile, or extract underlying AI models\n• Conduct automated stress testing, denial-of-service attacks, or systematic scraping\n• Use SKINIC to generate content that is defamatory, harmful, or violates third-party rights\n• Circumvent, disable, or interfere with rate limiting, authentication, or security mechanisms\n• Process data of minors under 13 without verifiable parental consent\n\nAPI Clients additionally must not:\n• Resell, sublicense, redistribute, or white-label API access without prior written consent\n• Share API keys across multiple organisations or clients without an Enterprise agreement\n• Present SKINIC outputs as progress reports, before/after comparisons, or product efficacy validation\n• Use optional fields such as skin_stability or skin_trajectory to imply that skin has improved, worsened, or that any product or routine is working\n• Present ingredient guidance as treatment, cure, or diagnosis of any medical condition\n\nStudio Clients additionally must not:\n• Create scan pages that impersonate another brand, business, or individual\n• Use scan pages to collect customer data for purposes beyond their stated beauty or cosmetic business\n• Misrepresent the purpose of the scan experience to end users (e.g., claiming it provides medical or clinical assessments)`,
  },
  {
    title: "5. Cosmetic-Only Disclaimer",
    body: `SKINIC is an AI-powered cosmetic profiling tool and is NOT a medical device, diagnostic tool, or clinical decision support system. All outputs — including skin-type profiling, visible trait scores, and ingredient guidance — are generated by machine learning models and are for informational, cosmetic, and beauty purposes only.\n\nSKINIC outputs:\n• Do not constitute medical advice, diagnosis, or treatment\n• Do not detect, screen for, or assess any disease or medical condition\n• Must not be used as the sole basis for any health decision\n\nRepeat scans: Each scan produces an independent cosmetic skin profile at the time of capture. SKINIC does not monitor treatment progress, validate product efficacy, or compare scans over time. Skin type, trait scores, and percentages may vary between scans due to lighting, environment, camera angle, time of day, and other photo conditions. A higher or lower score on a subsequent scan does not indicate improvement, worsening, or that any product or routine is working.\n\nBy using any SKINIC product, you agree to:\n• Display a clear cosmetic-only disclaimer to your end users or Studio End Users\n• Obtain informed consent from users before processing their images or biometric data\n• Not represent SKINIC outputs as clinical, medical, or diagnostic findings\n• Not present repeat scans as progress reports or product efficacy validation\n• Not present ingredient guidance as treatment for any medical condition\n\nStudio Clients must ensure their branded scan page includes a visible disclaimer stating that results are for cosmetic purposes only and are not medical advice.`,
  },
  {
    title: "6. End User & Studio End User Obligations",
    body: `If you are integrating SKINIC (via API or Studio) into a product or platform serving end users, you are solely responsible for:\n\n• Obtaining all necessary consents from your end users for data collection and AI-based profiling\n• Providing end users with a clear privacy notice that covers SKINIC data processing\n• Ensuring your product complies with applicable consumer protection and data protection laws in your jurisdiction\n• Handling all end user complaints, data requests (including access and deletion), and disputes related to your product\n\nStudio Clients have additional obligations:\n• You act as Data Controller for your Studio End Users' data (names, emails, scan results)\n• You must inform Studio End Users that their skin profile data is collected and stored\n• You must provide Studio End Users a mechanism to request deletion of their data from your customer database\n• You must not use Studio End User data for purposes beyond your stated cosmetic business (e.g., selling to third parties)\n\nThinking Studio LLC has no direct relationship with your end users or Studio End Users and accepts no liability arising from your product's or Studio's use of the SKINIC service.`,
  },
  {
    title: "7. Usage Limits & Quotas",
    body: `Each subscription tier includes defined scan quotas and rate limits as published on our pricing page.\n\nAPI Clients: Rate limits apply per API key in requests per minute. Exceeding rate limits results in HTTP 429 responses.\n\nStudio Clients: Scan quotas apply to your branded scan page on a monthly basis. Once exhausted, new scans will be paused until the next billing cycle or upon upgrade.\n\nSustained or deliberate abuse of limits, including via multiple accounts or API keys, may result in account suspension. We reserve the right to temporarily throttle or suspend service to protect platform stability. Limits may be adjusted with 14 days' notice for existing subscribers.`,
  },
  {
    title: "8. Payment, Billing & Refunds",
    body: `Paid subscriptions are billed monthly in advance. Payment is processed by Paddle.com as Merchant of Record. By subscribing, you authorise Paddle to charge your payment method on a recurring monthly basis until you cancel.\n\nRefund Policy:\n• Refund requests submitted within 7 days of the initial charge will be reviewed on a case-by-case basis\n• We do not offer pro-rated refunds for unused portions of a billing cycle after 7 days\n• Refunds will not be issued for accounts suspended due to Terms violations\n• To request a refund, email skinic@thinkingstudio.ai with your account email and reason\n\nPrices are listed in USD. Applicable taxes may be added at checkout depending on your jurisdiction.\n\nStudio Clients: Subscription tier governs the monthly scan quota for your branded scan page. Downgrading your plan does not automatically delete your customer database, but active scan access will be capped to the lower tier's quota.`,
  },
  {
    title: "9. Cancellation & Data on Termination",
    body: `You may cancel your subscription at any time through your dashboard (API Clients) or Studio (Studio Clients) or by contacting us. Cancellation takes effect at the end of your current billing cycle. You will retain access until the period ends.\n\nUpon account cancellation or termination:\n• API Clients: API keys are deactivated. Usage history is retained for 90 days, then deleted.\n• Studio Clients: Your branded scan page will become inactive. Your customer database, catalog, and scan records will be retained for 30 days after cancellation to allow you to export data (CSV). After 30 days, all Studio data including customer records will be permanently deleted.\n\nWe may cancel or suspend your account immediately for material breaches of these Terms. We recommend exporting your customer data before cancelling your Studio subscription.`,
  },
  {
    title: "10. Intellectual Property",
    body: `All intellectual property in the SKINIC API, AI models, documentation, and platform remains the exclusive property of Thinking Studio LLC. Nothing in these Terms grants you any ownership rights. You retain ownership of all data you submit to the API. By using the API, you grant us a limited, non-exclusive licence to process your submitted data solely to provide the service.`,
  },
  {
    title: "11. Confidentiality",
    body: `If you receive access to non-public information about the SKINIC platform (including beta features, pricing, roadmap, or technical specifications) in connection with your use of the service, you agree to treat such information as confidential and not disclose it to third parties without our written consent.`,
  },
  {
    title: "12. Warranty Disclaimer",
    body: `THE SKINIC API IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL COMPONENTS. AI MODEL OUTPUTS MAY CONTAIN ERRORS AND SHOULD NOT BE RELIED UPON AS DEFINITIVE.`,
  },
  {
    title: "13. Limitation of Liability",
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THINKING STUDIO LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS INTERRUPTION.\n\nOUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU IN THE THREE MONTHS PRECEDING THE CLAIM OR (B) USD $100.`,
  },
  {
    title: "14. Indemnification",
    body: `You agree to indemnify, defend, and hold harmless Thinking Studio LLC, its officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising from: (a) your use of the API in violation of these Terms; (b) your product's infringement of any third-party rights; (c) any claims by your end users relating to your product; or (d) your breach of any applicable law or regulation.`,
  },
  {
    title: "15. Service Modifications & Termination",
    body: `We reserve the right to modify, suspend, or discontinue any part of the service at any time. For material changes affecting paid subscribers, we will provide at least 30 days' notice. We may terminate accounts that violate these Terms, engage in fraudulent activity, or have unpaid balances, without prior notice in serious cases.`,
  },
  {
    title: "16. Changes to Terms",
    body: `We may update these Terms from time to time. We will notify you of material changes via email to your registered address or via an in-dashboard notice. Your continued use of the service after the effective date of changes constitutes acceptance of the updated Terms. If you do not agree to the changes, you must cancel your subscription before the effective date.`,
  },
  {
    title: "17. Governing Law & Dispute Resolution",
    body: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any dispute arising from or relating to these Terms shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration under the rules of the American Arbitration Association. Each party waives the right to a jury trial and to participate in class action proceedings.`,
  },
  {
    title: "18. AI Output Accuracy Disclaimer",
    body: `SKINIC's AI models are trained on large datasets but may produce inaccurate, incomplete, or inappropriate outputs including but not limited to:\n\n• Miscategorisation of skin type or visible traits\n• Incorrect ingredient guidance\n• Inconsistent results in visible trait scoring\n• Outputs that vary across similar inputs (model non-determinism)\n\nWE MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR SUITABILITY OF ANY AI-GENERATED OUTPUT. YOU ASSUME ALL RISK ASSOCIATED WITH RELIANCE ON SKINIC OUTPUTS. Thinking Studio LLC shall have no liability for any harm, decision, or action taken in reliance on AI outputs, regardless of whether such outputs were accurate or inaccurate.`,
  },
  {
    title: "19. Force Majeure",
    body: `Thinking Studio LLC shall not be liable for any failure or delay in performance of its obligations under these Terms arising from causes beyond our reasonable control, including but not limited to:\n\n• Acts of God, natural disasters, public emergencies, or pandemics\n• Failure or interruption of third-party infrastructure (including Supabase, Railway, Paddle, Cloudflare, AWS, or other service providers)\n• Cyberattacks, DDoS attacks, or malicious intrusions beyond our reasonable security measures\n• Internet or telecommunications outages\n• Government actions, sanctions, or regulatory changes\n• Labour disputes or shortages\n\nIn such events, our obligations shall be suspended for the duration of the force majeure event. We will notify affected users as soon as practicable.`,
  },
  {
    title: "20. Third-Party Services Disclaimer",
    body: `The SKINIC platform relies on third-party service providers including Supabase (database), Railway (hosting), Paddle (payments), and Cloudflare (network). We are not responsible for:\n\n• Outages, data loss, or service degradation caused by these third parties\n• Billing errors or disputes initiated by Paddle as Merchant of Record\n• Security incidents originating from third-party infrastructure\n• Changes to third-party APIs or services that affect SKINIC functionality\n\nYour use of Paddle's payment services is additionally governed by Paddle's own Terms of Service and Privacy Policy. We recommend reviewing these before subscribing.`,
  },
  {
    title: "21. Feedback & Testimonials",
    body: `If you submit feedback, bug reports, feature suggestions, or testimonials regarding the SKINIC service ("Feedback"), you grant Thinking Studio LLC a perpetual, irrevocable, worldwide, royalty-free licence to use, reproduce, modify, and incorporate such Feedback into our products and services without compensation or attribution. You represent that any Feedback you provide does not infringe any third-party rights.`,
  },
  {
    title: "22. Beta Features & Experimental Endpoints",
    body: `From time to time, we may offer access to beta features, experimental endpoints, or early-access functionality (collectively "Beta Features"). Beta Features are provided "AS IS" without any warranty and may be modified, suspended, or discontinued at any time without notice. We accept no liability for any data loss, errors, or damages arising from your use of Beta Features. Beta Features must not be used in production environments serving end users without our express written consent.`,
  },
  {
    title: "24. Regulatory & Jurisdiction",
    body: `SKINIC is offered and marketed as a cosmetic beauty and skin-profiling tool. Laws and regulations governing AI, software, cosmetics, and health-related products differ by country and region — including but not limited to the United States (FDA), European Union (MDR / AI Act), United Kingdom, Malaysia (NPRA), and others.\n\nThinking Studio LLC makes no representation that SKINIC is approved, registered, or exempt in any specific jurisdiction. You are solely responsible for:\n\n• Determining whether your use of SKINIC complies with applicable laws in your market\n• Obtaining any registrations, approvals, or legal reviews required before offering SKINIC-powered features to your end users\n• Ensuring your product copy, UX, and marketing remain within cosmetic/informational claims\n\nIf you are unsure about regulatory requirements in your jurisdiction, consult qualified legal counsel before launching a consumer-facing integration.`,
  },
  {
    title: "23. General Provisions",
    body: `These Terms constitute the entire agreement between you and Thinking Studio LLC regarding the SKINIC service and supersede all prior agreements. If any provision is found unenforceable, the remaining provisions remain in full effect. Our failure to enforce any right or provision shall not constitute a waiver of that right. You may not assign your rights under these Terms without our written consent. We may assign our rights to a successor entity in connection with a merger, acquisition, or sale of substantially all assets. Any notice to us must be sent to skinic@thinkingstudio.ai and will be effective upon our written acknowledgement.`,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-20">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="inline-flex items-center gap-2 mb-8 text-white/40 hover:text-white/70 text-sm transition-colors">
            ← Back to skinic.app
          </Link>
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-white/40 text-sm">Last updated: June 2026 · Thinking Studio LLC · Covers SKINIC Studio &amp; SKINIC API</p>
        </div>

        {/* Cosmetic-only disclaimer highlight */}
        <div className="card-glass rounded-2xl p-6 border border-amber-500/20 bg-amber-500/5 mb-6">
          <p className="text-amber-300 font-semibold text-sm mb-2">⚠ Cosmetic-Only Disclaimer — Please Read</p>
          <p className="text-white/50 text-sm leading-relaxed">
            SKINIC is an <strong className="text-white/70">AI cosmetic skin profiling tool, not a medical device</strong>. Outputs do not constitute medical advice, diagnosis, or treatment, and do not detect any disease or medical condition. You must display this disclaimer to your end users and must not represent SKINIC results as clinical, medical, or diagnostic findings.
          </p>
        </div>

        <div className="space-y-4">
          {sections.map((s) => {
            const anchor = s.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
            return (
              <div key={s.title} id={anchor} className="card-glass rounded-2xl p-6 scroll-mt-20">
                <p className="text-white font-semibold text-sm mb-3">{s.title}</p>
                <div className="text-white/45 text-sm leading-relaxed whitespace-pre-line">{s.body}</div>
              </div>
            );
          })}
        </div>

        <div className="card-glass rounded-2xl p-5 border border-white/5 text-center mt-6">
          <p className="text-white/30 text-xs">
            Questions? Email{" "}
            <a href="mailto:skinic@thinkingstudio.ai" className="text-violet-400">skinic@thinkingstudio.ai</a>
            {" · "}
            <Link href="/privacy" className="text-violet-400">Privacy Policy</Link>
            {" · "}
            <Link href="/" className="text-violet-400">skinic.app</Link>
          </p>
        </div>
      </div>
    </main>
  );
}
