import Link from "next/link";

export const metadata = {
  title: "Terms of Service — SKINIC",
  description: "Terms of Service for the SKINIC AI Skin Intelligence API.",
};

const sections = [
  {
    title: "1. Agreement to Terms",
    body: `By accessing or using the SKINIC API, dashboard, or any related services operated by Thinking Studio LLC ("Company", "we", "us", "our"), you ("Client", "you") agree to be bound by these Terms of Service ("Terms"). If you are using the API on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms. If you do not agree, you must not use our services.`,
  },
  {
    title: "2. Description of Service",
    body: `SKINIC provides an AI-powered skin intelligence API that performs cosmetic skin analysis, ingredient recommendation, and dermatological screening via REST API endpoints. The service is provided as-is for integration into third-party applications, platforms, and workflows. SKINIC is not a medical device and is not regulated as such in any jurisdiction.`,
  },
  {
    title: "3. Account Registration & Security",
    body: `You must provide accurate and complete information when creating your account. You are responsible for maintaining the confidentiality of your login credentials and API keys. You must notify us immediately at skinic@thinkingstudio.ai if you suspect unauthorised access to your account. We reserve the right to disable accounts we believe are compromised. Each API key must be used only by the authorised application for which it was issued.`,
  },
  {
    title: "4. Acceptable Use",
    body: `You agree to use SKINIC only for lawful purposes and in compliance with all applicable local, national, and international laws and regulations. You must not:\n\n• Resell, sublicense, redistribute, or white-label API access without prior written consent\n• Use the API to process data of minors under 13 without verifiable parental consent\n• Attempt to reverse-engineer, decompile, or extract underlying AI models\n• Conduct automated stress testing, denial-of-service attacks, or systematic scraping\n• Use the API to generate content that is defamatory, harmful, or violates third-party rights\n• Circumvent, disable, or interfere with rate limiting, authentication, or security mechanisms\n• Share API keys across multiple organisations or clients without an Enterprise agreement`,
  },
  {
    title: "5. Medical & Clinical Disclaimer",
    body: `SKINIC is an AI-powered screening tool and is NOT a medical device, diagnostic tool, or clinical decision support system. All outputs — including skin condition classifications, risk assessments, and ingredient recommendations — are generated by machine learning models and are for informational and cosmetic purposes only.\n\nSKINIC outputs:\n• Do not constitute medical advice, diagnosis, or treatment\n• Must not replace consultation with a licensed dermatologist or physician\n• Must not be used as the sole basis for clinical decisions\n\nBy integrating SKINIC into your product, you agree to:\n• Display a clear medical disclaimer to your end users\n• Obtain informed consent from users before processing their biometric data\n• Not represent SKINIC outputs as clinical or medical findings`,
  },
  {
    title: "6. End User Obligations",
    body: `If you are integrating SKINIC into a product or platform serving end users, you are solely responsible for:\n\n• Obtaining all necessary consents from your end users for data processing\n• Providing your end users with a clear privacy notice covering SKINIC data processing\n• Ensuring your product complies with applicable consumer protection laws in your jurisdiction\n• Handling all end user complaints, data requests, and disputes related to your product\n\nThinking Studio LLC has no direct relationship with your end users and accepts no liability arising from your product's use of the SKINIC API.`,
  },
  {
    title: "7. API Rate Limits & Quotas",
    body: `Each subscription tier includes defined rate limits (requests per minute) and monthly call quotas as published on our pricing page. Exceeding rate limits will result in HTTP 429 responses. Sustained or deliberate abuse of rate limits, including via multiple API keys, may result in account suspension.\n\nWe reserve the right to temporarily throttle or suspend service to protect platform stability. Rate limits may be adjusted with 14 days' notice for existing subscribers.`,
  },
  {
    title: "8. Payment, Billing & Refunds",
    body: `Paid subscriptions are billed monthly in advance. Payment is processed by Paddle.com as Merchant of Record. By subscribing, you authorise Paddle to charge your payment method on a recurring monthly basis until you cancel.\n\nRefund Policy:\n• Refund requests submitted within 7 days of the initial charge will be reviewed on a case-by-case basis\n• We do not offer pro-rated refunds for unused portions of a billing cycle after 7 days\n• Refunds will not be issued for accounts suspended due to Terms violations\n• To request a refund, email skinic@thinkingstudio.ai with your account email and reason\n\nPrices are listed in USD. Applicable taxes may be added at checkout depending on your jurisdiction.`,
  },
  {
    title: "9. Cancellation",
    body: `You may cancel your subscription at any time through your dashboard or by contacting us. Cancellation takes effect at the end of your current billing cycle. You will retain access until the period ends. We may cancel or suspend your account immediately for material breaches of these Terms.`,
  },
  {
    title: "10. Intellectual Property",
    body: `All intellectual property in the SKINIC API, AI models, documentation, and platform remains the exclusive property of Thinking Studio LLC. Nothing in these Terms grants you any ownership rights. You retain ownership of all data you submit to the API. By using the API, you grant us a limited, non-exclusive licence to process your submitted data solely to provide the service.`,
  },
  {
    title: "11. Confidentiality",
    body: `If you receive access to non-public information about the SKINIC platform (including beta features, pricing, roadmap, or technical specifications) in connection with your use of the service, you agree to treat such information as confidential and not disclose it to third parties without our written consent.`,
  },
  {
    title: "12. Warranty Disclaimer",
    body: `THE SKINIC API IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL COMPONENTS. AI MODEL OUTPUTS MAY CONTAIN ERRORS AND SHOULD NOT BE RELIED UPON AS DEFINITIVE.`,
  },
  {
    title: "13. Limitation of Liability",
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THINKING STUDIO LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS INTERRUPTION.\n\nOUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU IN THE THREE MONTHS PRECEDING THE CLAIM OR (B) USD $100.`,
  },
  {
    title: "14. Indemnification",
    body: `You agree to indemnify, defend, and hold harmless Thinking Studio LLC, its officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising from: (a) your use of the API in violation of these Terms; (b) your product's infringement of any third-party rights; (c) any claims by your end users relating to your product; or (d) your breach of any applicable law or regulation.`,
  },
  {
    title: "15. Service Modifications & Termination",
    body: `We reserve the right to modify, suspend, or discontinue any part of the service at any time. For material changes affecting paid subscribers, we will provide at least 30 days' notice. We may terminate accounts that violate these Terms, engage in fraudulent activity, or have unpaid balances, without prior notice in serious cases.`,
  },
  {
    title: "16. Changes to Terms",
    body: `We may update these Terms from time to time. We will notify you of material changes via email to your registered address or via an in-dashboard notice. Your continued use of the service after the effective date of changes constitutes acceptance of the updated Terms. If you do not agree to the changes, you must cancel your subscription before the effective date.`,
  },
  {
    title: "17. Governing Law & Dispute Resolution",
    body: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any dispute arising from or relating to these Terms shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration under the rules of the American Arbitration Association. Each party waives the right to a jury trial and to participate in class action proceedings.`,
  },
  {
    title: "18. General Provisions",
    body: `These Terms constitute the entire agreement between you and Thinking Studio LLC regarding the SKINIC service and supersede all prior agreements. If any provision is found unenforceable, the remaining provisions remain in full effect. Our failure to enforce any right or provision shall not constitute a waiver. You may not assign your rights under these Terms without our written consent. We may assign our rights to a successor entity in connection with a merger or acquisition.`,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-20">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="inline-flex items-center gap-2 mb-8 text-white/40 hover:text-white/70 text-sm transition-colors">
            ← Back to skinic.app
          </Link>
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-white/40 text-sm">Last updated: June 2026 · Thinking Studio LLC · Effective immediately upon account creation</p>
        </div>

        {/* Medical disclaimer highlight */}
        <div className="card-glass rounded-2xl p-6 border border-amber-500/20 bg-amber-500/5 mb-6">
          <p className="text-amber-300 font-semibold text-sm mb-2">⚠ Medical Disclaimer — Please Read</p>
          <p className="text-white/50 text-sm leading-relaxed">
            SKINIC is an <strong className="text-white/70">AI screening tool, not a medical device</strong>. Outputs do not constitute medical advice, diagnosis, or treatment. You must display this disclaimer to your end users and must not represent SKINIC results as clinical findings. Always refer users to a licensed dermatologist for medical concerns.
          </p>
        </div>

        <div className="space-y-4">
          {sections.map((s) => (
            <div key={s.title} className="card-glass rounded-2xl p-6">
              <p className="text-white font-semibold text-sm mb-3">{s.title}</p>
              <div className="text-white/45 text-sm leading-relaxed whitespace-pre-line">{s.body}</div>
            </div>
          ))}
        </div>

        <div className="card-glass rounded-2xl p-5 border border-white/5 text-center mt-6">
          <p className="text-white/30 text-xs">
            Questions? Email{" "}
            <a href="mailto:skinic@thinkingstudio.ai" className="text-violet-400">skinic@thinkingstudio.ai</a>
            {" · "}
            <Link href="/privacy" className="text-violet-400">Privacy Policy</Link>
            {" · "}
            <Link href="/" className="text-violet-400">skinic.app</Link>
          </p>
        </div>
      </div>
    </main>
  );
}
