import Link from "next/link";

export const metadata = {
  title: "How SKINIC Works — Transparency",
  description: "How SKINIC generates cosmetic skin profiles from your photo — pipeline, sources, and limitations.",
};

const pipelineSteps = [
  {
    step: "1",
    title: "Your photo",
    body: "Every scan starts with the image you submit — camera capture in Studio or mobile, or image upload via API. No photo, no profile. SKINIC does not pull pre-made results from a database of faces.",
  },
  {
    step: "2",
    title: "Image preparation",
    body: "The pipeline checks image quality (blur, exposure), confirms skin is present, crops to the face region, and normalizes lighting. Poor photos may receive a quality warning — scores reflect conditions at capture time.",
  },
  {
    step: "3",
    title: "Layer 1 — SKINIC Vision (skin type)",
    body: "A vision transformer classifier reads visual patterns in your photo and outputs skin type probabilities: Dry, Normal, Oily, or Combination (when dry and oily signals are close). Includes confidence breakdown across all types.",
  },
  {
    step: "4",
    title: "Layer 2 — SKINIC Multi-Label (visible traits)",
    body: "A multi-label model scores five cosmetic concerns directly from the image: breakouts, dryness, oiliness, dark spots, and wrinkles. Three additional traits — redness, visible pores, and uneven pigmentation — are derived from colorimetry and texture signals already computed in the pipeline.",
  },
  {
    step: "5",
    title: "Layer 3 — SKINIC Deep Vision (texture embedding)",
    body: "A deep visual embedding model (6144 dimensions) extracts rich skin texture features from your photo. SKINIC derives cosmetic indicators from this embedding: evenness (uniformity), texture complexity, skin entropy, and feature balance. These are statistical descriptors for the current scan — not clinical measurements.",
  },
  {
    step: "6",
    title: "Layer 4 — SKINIC Blemish Guard (visible spots)",
    body: "An object-detection model locates visible blemish spots in the photo — spots, whiteheads, red bumps, and deep bumps — and counts them. Outputs include total visible spot count, coverage estimates, and a blemish visibility band (minimal to prominent). For cosmetic awareness only — not exact clinical counts.",
  },
  {
    step: "7",
    title: "Colour analysis (skin tone & season)",
    body: "Standard CIE LAB colorimetry (ITA angle) samples skin colour from the face region. Combined with undertone analysis, this produces Fitzpatrick-style tone classification, colour season guidance, and flattering / avoid colour families. Based on established colorimetry methods — not a separate AI guess.",
  },
  {
    step: "8",
    title: "Assembly — clarity score & insight",
    body: "A fixed formula combines concern scores, texture evenness, and visible blemish signals into a skin clarity score (0–100) and label (Excellent / Good / Fair / Needs Care). A short insight paragraph is generated by deterministic rules from the same signals — not hand-written by staff and not a separate LLM call during scan.",
  },
];

export default function HowItWorksPage() {
  return (
    <main className="min-h-screen px-6 py-20">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="inline-flex items-center gap-2 mb-8 text-white/40 hover:text-white/70 text-sm transition-colors">
            ← Back to skinic.app
          </Link>
          <h1 className="text-3xl font-bold text-white mb-2">How SKINIC Works</h1>
          <p className="text-white/40 text-sm">Transparency · July 2026 · Thinking Studio LLC</p>
        </div>

        <div className="card-glass rounded-2xl p-6 border border-emerald-500/20 bg-emerald-500/5 mb-6">
          <p className="text-emerald-300 font-semibold text-sm mb-2">In one sentence</p>
          <p className="text-white/60 text-sm leading-relaxed">
            SKINIC computes your cosmetic skin profile <strong className="text-white/80">automatically from your photo</strong> using
            four AI layers plus standard colorimetry — results are <strong className="text-white/80">never manually edited</strong> per user.
          </p>
        </div>

        <div className="card-glass rounded-2xl p-6 border border-white/8 mb-6">
          <p className="text-white font-semibold text-sm mb-3">What SKINIC does NOT do</p>
          <ul className="space-y-2 text-white/45 text-sm">
            <li>✕ Does not pick results from a pre-made database of profiles</li>
            <li>✕ Does not have staff manually type or adjust your scores</li>
            <li>✕ Does not diagnose diseases or screen for medical conditions</li>
            <li>✕ Does not compare your scan to others to rank you</li>
            <li>✕ Does not monitor whether products improved your skin over time</li>
          </ul>
        </div>

        <div className="space-y-4 mb-8">
          <p className="text-white/35 text-xs font-semibold uppercase tracking-wider px-1">The pipeline</p>
          {pipelineSteps.map((s) => (
            <div key={s.step} className="card-glass rounded-2xl p-6">
              <div className="flex items-start gap-4">
                <span className="shrink-0 w-8 h-8 rounded-lg bg-violet-600/20 border border-violet-500/30 flex items-center justify-center text-violet-300 text-sm font-bold">
                  {s.step}
                </span>
                <div>
                  <p className="text-white font-semibold text-sm mb-2">{s.title}</p>
                  <p className="text-white/45 text-sm leading-relaxed">{s.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="card-glass rounded-2xl p-6 border border-violet-500/20 bg-violet-500/5 mb-6">
          <p className="text-violet-300 font-semibold text-sm mb-3">Verify it yourself (reproducibility)</p>
          <p className="text-white/50 text-sm leading-relaxed mb-3">
            API and developer clients can submit the <strong className="text-white/70">same image file</strong> multiple times.
            Skin type, trait scores, and clarity score should be <strong className="text-white/70">highly consistent</strong> when
            lighting and crop are identical. Large differences between scans usually mean different photo conditions — not manual manipulation.
          </p>
          <p className="text-white/40 text-xs">
            Test with your API key via{" "}
            <a href="https://api.skinic.app/docs" className="text-violet-400 hover:text-violet-300" target="_blank" rel="noreferrer">
              api.skinic.app/docs
            </a>
            {" "}or our Postman collection.
          </p>
        </div>

        <div className="card-glass rounded-2xl p-6 border border-amber-500/20 bg-amber-500/5 mb-6">
          <p className="text-amber-300 font-semibold text-sm mb-3">Honest limitations</p>
          <ul className="space-y-2 text-white/50 text-sm leading-relaxed">
            <li>• AI models can misclassify — especially under poor lighting or unusual angles</li>
            <li>• Visible blemish mapping may miss small or deep spots; it is directional, not an exact count</li>
            <li>• Texture and clarity scores are cosmetic indicators for the current photo — not clinical measurements</li>
            <li>• Each scan is an independent snapshot; repeat scans are not progress reports</li>
            <li>• Ingredient guidance (optional, via <code className="text-white/60">/recommend</code>) is cosmetic only — powered by SKINIC AI and a 551-ingredient knowledge base</li>
          </ul>
        </div>

        <div className="card-glass rounded-2xl p-6 mb-6">
          <p className="text-white font-semibold text-sm mb-3">Open-source components</p>
          <p className="text-white/45 text-sm leading-relaxed">
            SKINIC builds on licensed open-source and third-party machine learning components.
            Required attributions are listed in our{" "}
            <a
              href="https://github.com/thinkingstudio-ai/SKINIC/blob/main/ACKNOWLEDGMENTS.md"
              className="text-violet-400 hover:text-violet-300"
              target="_blank"
              rel="noreferrer"
            >
              ACKNOWLEDGMENTS
            </a>
            {" "}file. Public documentation uses SKINIC-branded layer names; enterprise clients may request a technical integrity brief.
          </p>
        </div>

        <div className="card-glass rounded-2xl p-5 border border-white/5 text-center">
          <p className="text-white/30 text-xs leading-relaxed">
            SKINIC is a cosmetic beauty tool — not a medical device.{" "}
            <Link href="/terms" className="text-violet-400">Terms</Link>
            {" · "}
            <Link href="/privacy" className="text-violet-400">Privacy</Link>
            {" · "}
            <a href="mailto:skinic@thinkingstudio.ai" className="text-violet-400">skinic@thinkingstudio.ai</a>
          </p>
        </div>
      </div>
    </main>
  );
}
